include_directories(${CMAKE_CURRENT_LIST_DIR}/include)

file(GLOB_RECURSE CURRENT_SOURCES
        "${CMAKE_CURRENT_LIST_DIR}/src/*.cpp"
        )

set(CLAID_SOURCES ${CLAID_SOURCES} ${CURRENT_SOURCES})

file(GLOB_RECURSE CURRENT_IOS_M_SOURCES
        "${CMAKE_CURRENT_LIST_DIR}/ios/*.m"
        )
set(CLAID_IOS_SOURCES ${CLAID_IOS_SOURCES} ${CURRENT_IOS_M_SOURCES})

file(GLOB_RECURSE CURRENT_IOS_MM_SOURCES
        "${CMAKE_CURRENT_LIST_DIR}/ios/*.mm"
        )
set(CLAID_IOS_SOURCES ${CLAID_IOS_SOURCES} ${CURRENT_IOS_MM_SOURCES})

IF(EXISTS "${CMAKE_CURRENT_LIST_DIR}/java" AND IS_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/java")
        set(CLAID_JAVA_DIRECTORIES ${CLAID_JAVA_DIRECTORIES} ${CMAKE_CURRENT_LIST_DIR}/java)
endif()